services:
  mysql:
    image: mysql:9.1.0
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: hospital_legacy
    healthcheck:
      test: mysqladmin ping -u root -p $$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  hospital-legacy:
    image: hospital-legacy:latest
    build: .
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  mysql_data: