server:
  servlet:
    context-path: /api
  port: 8081
spring:
  application:
    name:
      hospital-legacy
  datasource:
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/hospital_legacy}
  jpa:
    show-sql: true